### ISSUE TITLE
Can we handle html redirection?

### ISSUE THREAD

**Issue by zuphilip** [kba/rssscrpr#16]
For example [this RSS feed](https://rssscrpr.herokuapp.com/api.php?url=http%3A%2F%2Fedoc.hu-berlin.de%2Fbrowsing%2Fseries%2Findex.php%3Fl[2]%3DEinrichtungen%26l[3]%3D%2BInstitut%2Bf%25C3%25BCr%2BBibliotheks-%2Bund%2BInformationswissenschaft%26c[3][corp_id]%3D1005140%26l[4]%3DBerliner%2BHandreichungen%2Bzur%2BBibliotheks-%2Bund%2BInformationswissenschaft%2B-%26c[4][series_id]%3D29309%26_%3Da2eab3eda1ae2dfb5a515aa93f7ef9e3&action=scrape-html&scraper=XpathScraper&scraper_xpathItem=%2F%2Ftr[%40class%3D%22bghellgrau%22]&scraper_xpathTitle=.%2F%2Fa&scraper_xpathLink=.%2F%2Fa%2F%40href&scraper_xpathAuthor=.%2Ftd[2]%2Ftext%28%29[1]&scraper_xpathDescription=.&scraper_feedTitle=Berliner+Handreichungen+zur+Bibliotheks-+und+Informationswissenschaft&scraper_feedDescription=Dokumente+im+Repository+der+HU+Berlin&fetcher=HttpFetcher&parser=HTMLParser) works by using the url http://edoc.hu-berlin.de/browsing/series/index.php?l[2]=Einrichtungen&l[3]=+Institut+f%C3%BCr+Bibliotheks-+und+Informationswissenschaft&c[3][corp_id]=1005140&l[4]=Berliner+Handreichungen+zur+Bibliotheks-+und+Informationswissenschaft+-&c[4][series_id]=29309&_=a2eab3eda1ae2dfb5a515aa93f7ef9e3. But if we instead a shorter url http://0cn.de/tbux which redirects to the actual page the following error occurs:

```
Failed to retrieve 'http://0cn.de/tbux': {
    "url": "http:\/\/0cn.de\/tbux",
    "content_type": "text\/html; charset=UTF-8",
    "http_code": 302,
    "header_size": 528,
    "request_size": 303,
    "filetime": -1,
    "ssl_verify_result": 0,
    "redirect_count": 0,
    "total_time": 1.052315,
    "namelookup_time": 0.252984,
    "connect_time": 0.342316,
    "pretransfer_time": 0.342762,
    "size_upload": 0,
    "size_download": 0,
    "speed_download": 0,
    "speed_upload": 0,
    "download_content_length": 0,
    "upload_content_length": 0,
    "starttransfer_time": 1.051267,
    "redirect_time": 0,
    "redirect_url": "http:\/\/edoc.hu-berlin.de\/browsing\/series\/index.php?l[2]=Einrichtungen&l[3]=+Institut+f\u00fcr+Bibliotheks-+und+Informationswissenschaft&c[3][corp_id]=1005140&l[4]=Berliner+Handreichungen+zur+Bibliotheks-+und+Informationswissenschaft+-&c[4][series_id]=29309&_=a2eab3eda1ae2dfb5a515aa93f7ef9e3",
    "primary_ip": "5.199.142.96",
    "certinfo": [],
    "primary_port": 80,
    "local_ip": "172.19.7.218",
    "local_port": 41420
}
```

**Comment by kba** [comment]
Should work now: 
- Import [the original link](https://rssscrpr.herokuapp.com/api.php?url=http%3A%2F%2Fedoc.hu-berlin.de%2Fbrowsing%2Fseries%2Findex.php%3Fl%5B2%5D%3DEinrichtungen%26l%5B3%5D%3D%2BInstitut%2Bf%25C3%25BCr%2BBibliotheks-%2Bund%2BInformationswissenschaft%26c%5B3%5D%5Bcorp_id%5D%3D1005140%26l%5B4%5D%3DBerliner%2BHandreichungen%2Bzur%2BBibliotheks-%2Bund%2BInformationswissenschaft%2B-%26c%5B4%5D%5Bseries_id%5D%3D29309%26_%3Da2eab3eda1ae2dfb5a515aa93f7ef9e3&action=scrape-html&scraper=XpathScraper&scraper_xpathItem=%2F%2Ftr%5B%40class%3D%22bghellgrau%22%5D&scraper_xpathTitle=.%2F%2Fa&scraper_xpathLink=.%2F%2Fa%2F%40href&scraper_xpathAuthor=.%2Ftd%5B2%5D%2Ftext%28%29%5B1%5D&scraper_xpathDescription=.&scraper_feedTitle=Berliner+Handreichungen+zur+Bibliotheks-+und+Informationswissenschaft&scraper_feedDescription=Dokumente+im+Repository+der+HU+Berlin&fetcher=HttpFetcher&parser=HTMLParser)
- Fetch
- Replace the URL with http://bit.ly/1ToVV3P
- Fetch
- -> Result should be the same.

**Comment by zuphilip** [comment]
Thank you! Yes, it works!
