### ISSUE TITLE
Allow setting Feed metadata

### ISSUE THREAD

**Issue by kba** [kba/rssscrpr#8]
link and title for the channel are currently empty and they should contain something reasonable to pass the [W3C RSS validation chec](https://validator.w3.org/feed/)

**Comment by zuphilip** [comment]
Okay, I mention that in #7. I don't see it currently in the online version. Is it working?

**Comment by kba** [comment]
It is now. But not sure whether escaping is done properly. Keeping this open for now

**Comment by kba** [comment]
Everything should be properly escaped now.
